name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build Windows Release
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: windows-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: windows-cargo-index-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache target directory
      uses: actions/cache@v3
      with:
        path: target
        key: windows-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

    - name: Build release
      run: cargo build --release --target x86_64-pc-windows-msvc

    - name: Create release directory
      run: |
        mkdir release-assets
        copy target\x86_64-pc-windows-msvc\release\desktop-app.exe release-assets\desktop-app-windows-x86_64.exe

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release-assets/desktop-app-windows-x86_64.exe
        draft: false
        prerelease: false
        body: |
          ## Windows Desktop Application Release
          
          ### Changes
          - Windows x64 executable included
          - Auto-update functionality enabled
          
          ### Installation
          1. Download `desktop-app-windows-x86_64.exe`
          2. Run the executable
          
          ### Requirements
          - Windows 10 or later
          - No additional dependencies required
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
